### PR TITLE
Fix osgi imports to allow exposing transactions as mbeans

### PR DESCRIPTION
**Pull request by karel1980**
Exposing these packages makes it possible to work with admin transactions in an osgi context.

### CODE REVIEW

**Comment by GuyPardon** [comment]
Included in the 4.0.6 :-)

**Comment by karel1980** [comment]
Thank you!

**Comment by tomdw** [comment]
@GuyPardon when will 4.0.6 be released?

**Comment by GuyPardon** [comment]
Yesterday, but due to work overload it's been lingering around :-) Any time between this week and the end of the month I would say...

**Pull request closed without merging**
