### PR TITLE
JMS: Wrap the new MessageConsumer-creating methods added in JMS 2.0

### PR DESCRIPTION
**Pull request by baryonix**
JMS 2.0 adds three new methods to the `Session` interface that create new types of `MessageConsumer`s:

- `createDurableConsumer`
- `createSharedConsumer`
- `createSharedDurableConsumer`

This change adds provisions for wrapping them in a similar fashion as we wrap `createConsumer`, so that they can be used with TransactionEssentials.

I'm aware that this does not bring full support for JMS 2.0 (which would require proxying the new `JMSContext` in addition to `Session` and creating wrappers for `JMSProducer` and `JMSConsumer`), but this change goes a long way to make these new JMS 2.0 features usable e.g. with Spring. Spring doesn't use `JMSContext`, but can make use of the mentioned 3 new method calls if configured to do so.

Without this change, attempting to use these features in Spring, the calls to these methods go through TransactionEssentials unwrapped and this causes some rather non-obvious misbehavior. Depending on your message broker, the calls may go through successfully (but be non-transactional without you noticing), or the session may go completely haywire due to making the calls in a wrong transactional state.

### CODE REVIEW

**Comment by GuyPardon** [comment]
Thanks a bunch :-) 

I will schedule this for the 4.0.7 update already.

Full JMS 2.0 will have to wait until we get easier proxy creation (currently scoped for 5.0 - for which we're migrating the backlog to GitHub slowly).

Meanwhile, allow me some time to look at the JMS 2.0 details so I understand things a bit better.

Cheers

**Comment by rob-valor** [comment]
Any news on this pull request? 5.0 is already released for a while but this pull request is still open without . Are there any concrete plans to support full JMS 2 now with 5.0 released?

**Comment by GuyPardon** [comment]
Hi,

We haven't included JMS 2.0 in 5.0 yet (will be in a later release). I am not sure if we can incorporate your contrib in 5.0 though - I will check again.

Thanks
Guy

**Comment by GuyPardon** [comment]
Thanks, we've (finally) incorporated your suggestions in the 6.0 codebase.

**Pull request closed without merging**
