### PR TITLE
Avoid PostgreSQL interleaving issues

### LINKED ISSUE #163: Unable to reuse a PostgreSQL connection in a transaction when specifying a default transaction isolation level
**Describe the bug**
When using a default transaction isolation level on `AtomikosDataSource` with an underlying `PGXADataSource`, it is not possible to take a connection from the data source twice in a transaction.

**To Reproduce**
The following test case demonstrates the issue
```
  private AtomikosDataSourceBean atomikosDataSource;
  private UserTransaction atomikosTransactionManager;

  @Before
  public void setUp() throws Exception {
    XADataSource dataSource = (XADataSource)Class.forName("org.postgresql.xa.PGXADataSource").newInstance();
    dataSource.getClass().getMethod("setURL", String.class).invoke(dataSource, "jdbc:postgresql://localhost:5432/postgres");
    dataSource.getClass().getMethod("setUser", String.class).invoke(dataSource, "postgres");
    dataSource.getClass().getMethod("setPassword", String.class).invoke(dataSource, "manager");

    final UserTransactionManager atomikosTransactionManager = new UserTransactionManager();
    atomikosTransactionManager.init();
    this.atomikosTransactionManager = atomikosTransactionManager;

    atomikosDataSource = new AtomikosDataSourceBean();
    atomikosDataSource.setMaxIdleTime(10*60);
    atomikosDataSource.setMinPoolSize(0);
    atomikosDataSource.setMaxPoolSize(5);
    atomikosDataSource.setUniqueResourceName("Test Data Source");
    atomikosDataSource.setXaDataSource(dataSource);
    atomikosDataSource.setDefaultIsolationLevel(Connection.TRANSACTION_READ_COMMITTED);
  }

  @After
  public void tearDown() {
    atomikosDataSource.close();
  }

  @Test
  public void testConnectionReuse() throws Exception {
    atomikosTransactionManager.begin();
    try {
      try (Connection connection = atomikosDataSource.getConnection()) {
        try (PreparedStatement statement = connection.prepareStatement("SELECT 1")) {
          statement.executeQuery();
        }
      }

      try (Connection connection = atomikosDataSource.getConnection()) {
        try (PreparedStatement statement = connection.prepareStatement("SELECT 1")) {
          statement.executeQuery();
        }
      }
    } finally {
      atomikosTransactionManager.rollback();
    }
  }
```

This results in the following warning and the then exception that fails the test

```
13:15:09,416 WARN  [com.atomikos.jdbc.internal.JdbcConnectionProxyHelper] (main) cannot set isolation level to 2
org.postgresql.util.PSQLException: Cannot change transaction isolation level in the middle of a transaction.
	at org.postgresql.jdbc.PgConnection.setTransactionIsolation(PgConnection.java:928)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.postgresql.ds.PGPooledConnection$ConnectionHandler.invoke(PGPooledConnection.java:337)
	at com.sun.proxy.$Proxy8.setTransactionIsolation(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.postgresql.xa.PGXAConnection$ConnectionHandler.invoke(PGXAConnection.java:148)
	at com.sun.proxy.$Proxy8.setTransactionIsolation(Unknown Source)
	at com.atomikos.jdbc.internal.JdbcConnectionProxyHelper.setIsolationLevel(JdbcConnectionProxyHelper.java:31)
	at com.atomikos.jdbc.internal.AtomikosXAPooledConnection.doCreateConnectionProxy(AtomikosXAPooledConnection.java:92)
	at com.atomikos.jdbc.internal.AtomikosXAPooledConnection.doCreateConnectionProxy(AtomikosXAPooledConnection.java:30)
	at com.atomikos.datasource.pool.AbstractXPooledConnection.createConnectionProxy(AbstractXPooledConnection.java:74)
	at com.atomikos.datasource.pool.ConnectionPoolWithConcurrentValidation.concurrentlyTryToRecycle(ConnectionPoolWithConcurrentValidation.java:50)
	at com.atomikos.datasource.pool.ConnectionPoolWithConcurrentValidation.recycleConnectionIfPossible(ConnectionPoolWithConcurrentValidation.java:31)
	at com.atomikos.datasource.pool.ConnectionPool.findExistingOpenConnectionForCallingThread(ConnectionPool.java:144)
	at com.atomikos.datasource.pool.ConnectionPool.borrowConnection(ConnectionPool.java:111)
	at com.atomikos.jdbc.internal.AbstractDataSourceBean.getConnection(AbstractDataSourceBean.java:349)
	at TestPostgresql.testConnectionReuse(TestPostgresql.java:60)
```

```
com.atomikos.datasource.ResourceException: XA resource 'Test Data Source': resume for XID 'XID: 31302E34342E32302E3134342E746D313634383231343130383934363030303031:31302E34342E32302E3134342E746D31' raised -3: the XA resource detected an internal error
	at com.atomikos.datasource.xa.XAResourceTransaction.resume(XAResourceTransaction.java:225)
	at com.atomikos.datasource.xa.session.BranchEnlistedStateHandler.<init>(BranchEnlistedStateHandler.java:40)
	at com.atomikos.datasource.xa.session.NotInBranchStateHandler.checkEnlistBeforeUse(NotInBranchStateHandler.java:46)
	at com.atomikos.datasource.xa.session.TransactionContext.checkEnlistBeforeUse(TransactionContext.java:58)
	at com.atomikos.datasource.xa.session.SessionHandleState.notifyBeforeUse(SessionHandleState.java:163)
	at com.atomikos.jdbc.internal.AtomikosJdbcConnectionProxy.enlist(AtomikosJdbcConnectionProxy.java:88)
	at com.atomikos.jdbc.internal.AtomikosJdbcConnectionProxy.updateTransactionContext(AtomikosJdbcConnectionProxy.java:61)
	at com.atomikos.jdbc.internal.AbstractJdbcConnectionProxy.prepareStatement(AbstractJdbcConnectionProxy.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.atomikos.util.DynamicProxySupport.callProxiedMethod(DynamicProxySupport.java:159)
	at com.atomikos.util.DynamicProxySupport.invoke(DynamicProxySupport.java:116)
	at com.sun.proxy.$Proxy10.prepareStatement(Unknown Source)
	at TestPostgresql.testConnectionReuse(TestPostgresql.java:61)
        ...
Caused by: org.postgresql.xa.PGXAException: Invalid protocol state requested. Attempted transaction interleaving is not supported. xid=XID: 31302E34342E32302E3134342E746D313634383231343130383934363030303031:31302E34342E32302E3134342E746D31, currentXid=null, state=IDLE, flags=2,097,152
	at org.postgresql.xa.PGXAConnection.start(PGXAConnection.java:210)
	at com.atomikos.datasource.xa.XAResourceTransaction.resume(XAResourceTransaction.java:219)
	... 47 more

```

**Additional context**

This can be avoided with a simple check in JdbcConnectionProxyHelper to avoid setting the isolation level if it is already correct.

### LINKED ISSUE #164: XA branch reuse can cause interleaving exceptions from the PostgreSQL driver
**Describe the bug**
Taking more than one connection in and out of the pool in a transaction with PostgreSQL can trigger interleaving exceptions, even though no intentional transaction interleaving is occurring. The issue occurs as when a connection is reused from the pool a new `TransactionContext` is created by the `SessionHandleState` but the `SiblingMapper` will try to reuse a XA branch if it can. The underlying `PostgresXAConnection` doesn't like the changing XIDs until the transaction is complete, even though they aren't used by the database itself. If the `SiblingMapper` finds a branch that has a different XID to the connection an interleaving exception will be thrown.

**To Reproduce**

The following test case demonstrates the issue

```
  private AtomikosDataSourceBean atomikosDataSource;
  private UserTransaction atomikosTransactionManager;

  @Before
  public void setUp() throws Exception {
    XADataSource dataSource = (XADataSource)Class.forName("org.postgresql.xa.PGXADataSource").newInstance();
    dataSource.getClass().getMethod("setURL", String.class).invoke(dataSource, "jdbc:postgresql://localhost:5432/postgres");
    dataSource.getClass().getMethod("setUser", String.class).invoke(dataSource, "postgres");
    dataSource.getClass().getMethod("setPassword", String.class).invoke(dataSource, "manager");

    final UserTransactionManager atomikosTransactionManager = new UserTransactionManager();
    atomikosTransactionManager.init();
    this.atomikosTransactionManager = atomikosTransactionManager;

    atomikosDataSource = new AtomikosDataSourceBean();
    atomikosDataSource.setMaxIdleTime(10*60);
    atomikosDataSource.setMinPoolSize(0);
    atomikosDataSource.setMaxPoolSize(5);
    atomikosDataSource.setUniqueResourceName("Test Data Source");
    atomikosDataSource.setXaDataSource(dataSource);
    atomikosDataSource.setDefaultIsolationLevel(Connection.TRANSACTION_READ_COMMITTED);
  }

  @After
  public void tearDown() {
    atomikosDataSource.close();
  }

  @Test
  public void testInterleaving() throws Exception {
    // Grab the 1st pooled connection outside a transaction
    Connection firstConnection = atomikosDataSource.getConnection();


    atomikosTransactionManager.begin();
    try {
      // 2nd connection will be linked to the 1st transaction branch
      try (Connection secondConnection = atomikosDataSource.getConnection()) {
        try (PreparedStatement statement1 = secondConnection.prepareStatement("SELECT 1")) {
          statement1.executeQuery();

          // Return the 1st connection and grab it again inside the transaction
          firstConnection.close();
          // 1st connection will be associated with the 2nd transaction branch
          try (Connection firstConnectionAgain = atomikosDataSource.getConnection()) {
            try (PreparedStatement statement2 = firstConnectionAgain.prepareStatement("SELECT 1")) {
              statement2.executeQuery();
            }
          }
        }
      }

      // Attempt to get the 1st connection again, this time it will be associated to the 1st transaction branch
      try (Connection firstConnectionAgain = atomikosDataSource.getConnection()) {
        try (PreparedStatement statement2 = firstConnectionAgain.prepareStatement("SELECT 1")) {
          statement2.executeQuery();
        }
      }
    } finally {
      atomikosTransactionManager.rollback();
    }
  }
```
This results in the following exception that fails the test

```
com.atomikos.datasource.ResourceException: XA resource 'Test Data Source': resume for XID 'XID: 31302E34342E32302E3134342E746D313634383538373530343134343030303031:31302E34342E32302E3134342E746D31' raised -3: the XA resource detected an internal error

	at com.atomikos.datasource.xa.XAResourceTransaction.resume(XAResourceTransaction.java:225)
	at com.atomikos.datasource.xa.session.BranchEnlistedStateHandler.<init>(BranchEnlistedStateHandler.java:40)
	at com.atomikos.datasource.xa.session.NotInBranchStateHandler.checkEnlistBeforeUse(NotInBranchStateHandler.java:46)
	at com.atomikos.datasource.xa.session.TransactionContext.checkEnlistBeforeUse(TransactionContext.java:58)
	at com.atomikos.datasource.xa.session.SessionHandleState.notifyBeforeUse(SessionHandleState.java:163)
	at com.atomikos.jdbc.internal.AtomikosJdbcConnectionProxy.enlist(AtomikosJdbcConnectionProxy.java:88)
	at com.atomikos.jdbc.internal.AtomikosJdbcConnectionProxy.updateTransactionContext(AtomikosJdbcConnectionProxy.java:61)
	at com.atomikos.jdbc.internal.AbstractJdbcConnectionProxy.prepareStatement(AbstractJdbcConnectionProxy.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.atomikos.util.DynamicProxySupport.callProxiedMethod(DynamicProxySupport.java:159)
	at com.atomikos.util.DynamicProxySupport.invoke(DynamicProxySupport.java:116)
	at com.sun.proxy.$Proxy10.prepareStatement(Unknown Source)
	at TestPostgresql.testInterleaving(TestPostgresql.java:96)
        ...
Caused by: org.postgresql.xa.PGXAException: Invalid protocol state requested. Attempted transaction interleaving is not supported. xid=XID: 31302E34342E32302E3134342E746D313634383538373530343134343030303031:31302E34342E32302E3134342E746D31, currentXid=null, state=IDLE, flags=2,097,152
	at org.postgresql.xa.PGXAConnection.start(PGXAConnection.java:215)
	at com.atomikos.datasource.xa.XAResourceTransaction.resume(XAResourceTransaction.java:219)
	... 47 more
```

**Additional context**

It may be possible to address this by attempting to reuse the `TransactionContext` which already has a link to the `XAResourceTransaction` that provided an XID to the connection.

_I understand that this project is not intended for support - because bug reports may or may not be considered for inclusion some day (in a future release). If this is issue is important to me then I can go to https://www.atomikos.com/Main/SupportOverview and arrange a paid support subscription._

### PR DESCRIPTION
**Pull request by capgen628**
Fixes #163 
Fixes #164

### CODE REVIEW

**Comment by gallyamb** [comment]
@GuyPardon hi! Can you give an answer to the question above? I'm very interested on merging this PR

**Comment by GuyPardon** [comment]
Thanks,

The isolation level fix is interesting, but the other part seems to conflict with a different way of solving this in our commercial distribution. So I don't think we can merge all of it. You may want to keep this in a branch of yours.

If you want to try out the way we solved this, please contact me for a free trial.

Apologies for not responding fast, a lot of notification end up in my spam lately.

**Comment by joshuapullin** [comment]
@GuyPardon will the fix you mention that is different end up in the next transaction-essentials release?

**Comment by GuyPardon** [comment]
@joshuapullin probably yes, but can you explain the motivation behind it so we can check what part to include or not?

**Comment by joshuapullin** [comment]
@GuyPardon We are trying to implement the transactions-remoting module using a microservice architecture. 
We use Postgres and when we get multiple requests for the same transaction boundary to the same microservice that holds the database, we get the interleaving issue. 

Multiple requests in the same transaction boundary to the same service was one of the scenarios I was testing to ensure all scenarios of REST transactions would be covered before I could roll it out entirely.

**Pull request closed without merging**
