### PR TITLE
dependency management to permit use of atomikos-parent at import scope

### PR DESCRIPTION
**Pull request by mbenson**
I was using `dependency-management`/`import` scope with `spring-boot-dependencies` and `modeshape-bom-embedded`, each of which import different artifacts from different versions of Atomikos OSS, and neither version being the latest release. In order to override, I must declare:

```
			<dependency>
				<groupId>com.atomikos</groupId>
				<artifactId>transactions-api</artifactId>
				<version>${atomikos-transactions.version}</version>
			</dependency>
			<dependency>
				<groupId>com.atomikos</groupId>
				<artifactId>transactions</artifactId>
				<version>${atomikos-transactions.version}</version>
			</dependency>
			<dependency>
				<groupId>com.atomikos</groupId>
				<artifactId>transactions-jta</artifactId>
				<version>${atomikos-transactions.version}</version>
			</dependency>
			<dependency>
				<groupId>com.atomikos</groupId>
				<artifactId>transactions-jdbc</artifactId>
				<version>${atomikos-transactions.version}</version>
			</dependency>
```

With the proposed change that would be as simple as:

```
			<dependency>
				<groupId>com.atomikos</groupId>
				<artifactId>atomikos-parent</artifactId>
				<version>${atomikos-transactions.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
```

### CODE REVIEW

**Comment by JaroKuruc** [comment]
@mbenson  I think a better solution would be to introduce new module `atomikos-bom` which would contain just dependency management entries.

**Comment by mbenson** [comment]
That would solve my problem as well; however, I chose the approach I did because if I it were my project I wouldn't want to have to manage the version numbers for all the interdependencies between the various atomikos modules.

**Comment by pascalleclercq** [comment]
Hi all,

concerning spring boot, if you have the atomikos starter in your classpath the only thing you have to do is to change the value of property

"atomikos.version" in your pom.xml

see documentation here :
https://www.atomikos.com/Documentation/SpringBootIntegration

Outside spring boot world, most of the time you only have to add 
<dependency>
	 <groupId>com.atomikos</groupId>
	<artifactId>transactions-jdbc</artifactId>
</dependency>
if you use JDBC or 
<dependency>
	 <groupId>com.atomikos</groupId>
	<artifactId>transactions-jms</artifactId>
</dependency>
if you use JMS 

much of other dependencies are transitives so that shouldn't be that much an issue.

**Comment by mbenson** [comment]
@pascalleclercq I wasn't aware that setting `atomikos.version` would work, and indeed, when I try it, it doesn't seem to. Beyond that, note again that I described having both Modeshape _and_ Spring Boot pulling in Atomikos artifacts, hence the version discrepancies.

**Comment by GuyPardon** [comment]
@mbenson @JaroKuruc Thanks for the suggestions, we will add a bom!

**Pull request closed without merging**
