### PR TITLE
Don't show the XA datasource password in clear text in the logs, show password placeholders

### PR DESCRIPTION
**Pull request by mches**
Omits the password property when printing all the properties of the XA datasource

### CODE REVIEW

**Comment by GuyPardon** [comment]
Hi Mark,

Thanks! Before we merge this: can you send your email address so we can send our contributor agreement?

Guy

**Comment by mches** [comment]
Done. 

I thought some more and perhaps it might be useful to know whether the password was present or absent. With the current pull request, it would no longer be possible to distinguish. Therefore, do you think it would be better to show a placeholder when the password is present? e.g. password=<password> or password=********. I could change the pull request.

**Comment by GuyPardon** [comment]
Yes, with asterisk placeholders might be better!

Thanks

Guy

On 20 Oct 2015, at 01:32, Mark Chesney <notifications@github.com> wrote:

Done.

I thought some more and perhaps it might be useful to know whether the password was present or absent. With the current pull request, it would no longer be possible to distinguish. Therefore, do you think it would be better to show a placeholder when the password is present? e.g. password= or password=********. I could change the pull request.

�

**Comment by mches** [comment]
Added a commit to show password placeholders when the data source password is present

**Comment by GuyPardon** [comment]
That�s great, thanks!

On 20 Oct 2015, at 22:12, Mark Chesney <notifications@github.com> wrote:

Added a commit to show password placeholders when the data source password is present

�

**Comment by JaroKuruc** [comment]
Some unit test coverage would be nice :)

**Comment by mches** [comment]
@JaroKuruc Pull requests welcome :grin:

**Comment by GuyPardon** [comment]
@Mark sorry about the delay - your contribution will get pulled/merged soon

**Pull request closed without merging**
